---

#
#
#

variables:
  IMAGE_NAME: "${CI_PROJECT_NAME}"
  IMAGE_TAGS: "${CI_COMMIT_REF_NAME}"
  SSH_PRIVATE_KEY: SECURE

stages:
  - build

build-container:
  stage: build
  script:
    - REGISTRIES=$(dig _docker-registry._tcp.example.com IN SRV +short | cut -d ' ' -f 4)
    - BUILD_ID=$(docker build
        --pull
        --quiet
        --shm-size=256M
        --build-arg SSH_PRIVATE_KEY="${SSH_PRIVATE_KEY}"
        --build-arg PROJECT_NAMESPACE=${CI_PROJECT_NAMESPACE}
        --build-arg PROJECT_NAME=${CI_PROJECT_NAME}
        $(for REGISTRY in ${REGISTRIES}; do
            for TAG in ${IMAGE_TAGS}; do
              echo --tag\ ${REGISTRY::-1}/${IMAGE_NAME}:${TAG}\ ;
            done
        done)
        --file docker/Dockerfile .)
    - for REGISTRY in ${REGISTRIES}; do
        for TAG in ${IMAGE_TAGS}; do
          docker push ${REGISTRY::-1}/${IMAGE_NAME}:${TAG};
        done
      done
    - docker rmi -f ${BUILD_ID}
  tags:
    - shell
    - builder
    - uk
